create table if not exists public.conversations (
 id bigint generated by default as identity primary key,
 user_id uuid not null references auth.users(id) on delete cascade,
 title text default 'Nova conversa',
 messages jsonb not null default '[]'::jsonb,
 created_at timestamptz default now(),
 updated_at timestamptz default now()
);
alter table public.conversations enable row level security;
drop policy if exists "users own conversations" on public.conversations;
create policy "users own conversations" on public.conversations for all to authenticated using (auth.uid()=user_id) with check (auth.uid()=user_id);
